LABELS = {
    "en": {
        "executive_overview": "Executive Overview",
        "customer_explorer": "Customer Explorer",
        "customer_360": "Customer 360",
        "route_analytics": "Route Analytics",
        "ai_assistant": "AI Assistant",
        "total_customers": "Total Customers",
        "avg_clv": "Avg CLV",
        "total_revenue": "Total Revenue",
        "churn_risk": "Churn Risk",
        "open_tickets": "Open Tickets",
        "gold_tier": "Gold",
        "silver_tier": "Silver",
        "churn_risk_tier": "Churn Risk",
        "hotel": "Hotel",
        "flight": "Flight",
        "experience": "Experience",
        "omnichannel": "Omnichannel",
        "identity_confidence": "Identity Confidence",
        "high": "High",
        "phone_bridge": "Phone Bridge",
        "email": "Email",
        "recommended_action": "Recommended Action",
        "reactivate": "Reactivate",
        "cross_sell": "Cross-Sell",
        "retain": "Retain",
        "reengage": "Re-engage",
        "coming_soon": "Coming in Phase 6",
        "no_customer_selected": "Select a customer to view 360 profile",
        "loading": "Loading...",
        "error": "Error",
        "back_to_explorer": "Back to Customer Explorer",
    },
}
